---
- name: configure | deploy systemd configuration
  template:
    src: "k3s-{{ k3s_type }}.service.j2"
    dest: /etc/systemd/system/k3s.service
    owner: root
    group: root
    mode: 0644
  notify: "restart k3s"

- name: configure | create symbolic link
  file:
    src: "/usr/local/bin/k3s"
    dest: "/usr/local/bin/{{ item }}"
    state: link
  loop:
    - kubectl
    - crictl

- name: configure | flush handlers
  meta: flush_handlers

- name: configure | wait until node token is generated
  wait_for:
    path: /var/lib/rancher/k3s/server/node-token
  when: k3s_type == 'master'

- name: configure | get node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_cluster_token_raw
  when: k3s_type == 'master'

- name: configure | set fact k3s_cluster_token
  set_fact:
    k3s_cluster_token: "{{ k3s_cluster_token_raw['content'] | b64decode | replace('\n', '') }}"
  when: k3s_type == 'master'

- name: configure | flush_handlers
  meta: flush_handlers
