---
- name: install | download k3s binary
  get_url:
    url: https://github.com/rancher/k3s/releases/download/v{{ k3s_version }}/k3s
    dest: /usr/local/bin/k3s
    validate_certs: yes
    owner: root
    group: root
    mode: 755
