---
- name: Destroy
  hosts: localhost
  gather_facts: false
  tasks:
    - name: destroy vm
      shell: footloose delete
      ignore_errors: yes
    - name: remove footloose configuration file
      file:
        path: "{{ playbook_dir }}/footloose.yaml"
        state: absent
      ignore_errors: yes
