---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint: |
  yamllint --config-file=.yamllint .
  ansible-lint --exclude molecule
  flake8
platforms:
  - name: k3s-master0
    groups:
      - k3s-master
      - all
    image: "${MOLECULE_DOCKER_IMAGE:-geerlingguy/docker-ubuntu2004-ansible}:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    networks:
      - name: k3snet
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: report.xml
  lint:
    name: flake8
