---
dependency:
  name: galaxy
  enabled: False
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  - name: master
    groups:
      - k3s-master
      - all
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: report.xml
  lint:
    name: flake8
