---
dependency:
  name: galaxy
  enabled: False
driver:
  name: docker
lint: |
  yamllint --config-file=.yamllint .
  ansible-lint --exclude molecule
  flake8
platforms:
  - name: k3s-master0
    groups:
      - k3s-master
      - all
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: report.xml
  lint:
    name: flake8
